name: CI Pipeline (PRs and pushes main)
run-name: Merged to main by ${{ github.actor }}
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package with pip
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run tests
        run: |
          pytest

      - name: Run CI/CD validation scripts for MITE entries
        run: |
          python .github/mite_validation.py